import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Moje Next appka",
  description: "Generated by create next app",
};

export interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="cs">
      <body className="p-5">
        <h1 className="text-2xl font-bold">Můj skvělý web</h1>
        {children}
      </body>
    </html>
  );
}
